### PR TITLE
xsd2json: Basic support for attribute and value restrictions

### LINKED ISSUE #82: xsd2json: Attribute appears twice in restrictions
When an attribute of a `complexType` is restricted further, it appears twice in the output JSON.

In the following example, the attribute `foo` is optional in `BaseType`, but restricted to be required in `FooType`:

```xml
<schema xmlns:foo="http://example.com/foo" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/foo" elementFormDefault="qualified">
  <complexType name="BaseType">
    <simpleContent>
      <extension base="string">
        <attribute name="foo" type="string" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="FooType">
    <simpleContent>
      <restriction base="foo:BaseType">
        <attribute name="foo" type="string" use="required"/>
      </restriction>
    </simpleContent>
  </complexType>
  <element name="Main">
    <complexType>
      <sequence>
        <element name="Foo" type="foo:FooType"/>
      </sequence>
    </complexType>
  </element>
</schema>
```

Current output (relevant part):

```json
        {
          "values": [],
          "type": "string",
          "ns": 3,
          "name": "Foo",
          "element": true,
          "attributes": [
            {
              "values": [],
              "type": "string",
              "ns": 3,
              "name": "foo",
              "attribute": true
            },
            {
              "values": [],
              "type": "string",
              "ns": 3,
              "name": "foo",
              "attribute": true
            }
          ],
          "elements": []
        }
```

Expected output (relevant part):

```json
        {
          "values": [],
          "type": "string",
          "ns": 3,
          "name": "Foo",
          "element": true,
          "attributes": [
            {
              "values": [],
              "type": "string",
              "ns": 3,
              "name": "foo",
              "attribute": true
            }
          ],
          "elements": []
        }
```

### PR DESCRIPTION
**Pull request by vog**
Fixed #82.

This pull request depends on the following other pull requests:

* #87 (otherwise tests will fail)
* #89 (otherwise merge will fail)

### CODE REVIEW

**Comment by vog** [comment]
Rebased on current master. Ready to merge. Please review.

**Comment by bbpennel** [comment]
After pulling in changes from the master branch all the tests were passing except for the mods one:
`issue-078-mods-3-4 | Could not resolve reference to type 3:string from definition type`
Is that passing for you?

**Comment by vog** [comment]
Current master (8435c5066cb7e5f51c0309f479add9524d06249e) shows all green for me.

I rebased this pull request to that current master, and still everything green.

**Comment by bbpennel** [comment]
Okay, they are all passing for me now too after the rebasing

**Pull request merged**
