### PR TITLE
xsd2json: Use substitution group type only when no type is given

### LINKED ISSUE #84: xsd2json: Missing sub elements when using substitutionGroup
The following Schema defines 

```xml
<schema xmlns:foo="http://example.com/foo" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/foo" elementFormDefault="qualified">
  <complexType name="BaseType">
    <sequence/>
  </complexType>
  <complexType name="FooType">
    <complexContent>
      <restriction base="foo:BaseType">
        <sequence>
          <element name="Bar">
            <complexType>
              <simpleContent>
                <extension base="string">
                  <attribute name="bar" type="string"/>
                </extension>
              </simpleContent>
            </complexType>
          </element>
        </sequence>
      </restriction>
    </complexContent>
  </complexType>
  <element name="Base" type="foo:BaseType"/>
  <element name="Foo" type="foo:FooType" substitutionGroup="foo:Base"/>
</schema>
```

Current output (relevant part):

```json
    {
      "values": [],
      "type": null,
      "ns": 3,
      "name": "Foo",
      "element": true,
      "attributes": [],
      "elements": []
    }
```

Expected output (relevant part):

```json
    {
      "values": [],
      "type": null,
      "ns": 3,
      "name": "Foo",
      "element": true,
      "attributes": [],
      "elements": [
        {
          "values": [],
          "type": "string",
          "ns": 3,
          "name": "Bar",
          "element": true,
          "attributes": [
            {
              "values": [],
              "type": "string",
              "ns": 3,
              "name": "bar",
              "attribute": true
            }
          ],
          "elements": []
        }
      ]
    }
```

Workarounds:

* When removing `substitutionGroup="foo:Base"`, the expected schema is returned.

### PR DESCRIPTION
**Pull request by vog**
Fixes #84.

This pull request depends on pull request #90.

### CODE REVIEW

**Comment by bbpennel** [comment]
This change looks good overall, but I've added a failing test for another of the schemas from the demo page.

**Comment by vog** [comment]
It seems this additional test got lost while I was rebasing to the latest master. Would you mind re-adding it? Also, it is related to this pull request or the other one (#90)?

**Comment by bbpennel** [comment]
I've added the test back in, looks like its passing now.  That was easy!

**Comment by vog** [comment]
Great!

**Pull request merged**
